name: ${project.name}
author: ${plugin.author}
description: ${project.description}
main: ${plugin.mainClass}
version: ${project.version}
api-version: ${plugin.api-version}
commands:
  sipauth:
    description: SimpleIPAuth commands
    usage: '/<command> [ list | add | remove | reload | clearcache ]'
permissions:
  sipauth.bypass:
    description: Bypass the IP check.
    default: false
  sipauth.reload:
    description: Reload SimpleIPAuth logins and configuration.
    default: op
  sipauth.manage:
    description: Manage all players.
    default: op